### ISSUE TITLE
rbh_to_subway fails with no error message

### ISSUE THREAD

**Issue by Mia1349** [conchoecia/odp#29] opened 2023-05-30 13:23 UTC
Hello Darrin, 

This is Mia, congratulations on the Nature paper! It's nice to see the advancements you made to the odp software.  I enjoy using it for my synteny analysis.

Now, I have two new genomes and I want to create the kind of ribbon plot presented in your nature paper(Fig.1d), the plot order should be my species, scallop, lancelet, and cnidaria.  I followed the instructions you mentioned in other issues, and gave the order of the species and feeding it a list of results from the odp pipeline, but the pipeline shuts down very quickly,  I only have one output file, sp_to_chr_to_size.tsv,  I attach the log file and the config file. 

Maybe I missed a few things here? The plot order I gave is  
  - TCS
  - TSS
  - PMA
  - BFL
  - RHO

and the normal odp pipeline was run between TCS and TSS, TSS and PMA, PMA and BFL, BFL and RHO, the resulting rbh
file were used to generate the subway plot(the config file). Any ideas of how to fix that?

Thank you in advance for your help! 

Mia

[2023-05-31T205331.995384.snakemake.log](https://github.com/conchoecia/odp/files/11600228/2023-05-31T205331.995384.snakemake.log)
[config.txt](https://github.com/conchoecia/odp/files/11600270/config.txt)

**Comment by conchoecia** [comment] 2023-05-30 18:38
Thanks w/r/t the paper, and thanks for trying `odp`!

FYI - I just renamed the script `rbh_to_subway` to `odp_rbh_to_ribbon`. [See the new instructions I added.](https://github.com/conchoecia/odp#use-case---make-ribbon-diagrams-of-conserved-linkages-between-genomes) I recommend doing a `git pull` to update the file names.

Just some comments, I recommend specifying the directory containing the `.rbh` files instead of specifying each file. I might deprecate the `rbh_files_in_order` functionality in the future because it is harder to use.

```yaml
#rbh_files_in_order:

rbh_directory:   /home/liuhy/Source_Data/chequ/odp/new_odp/RBHs/TSS_TCS/odp/step2-figures/synteny_coloredby_BCnS_LGs/
```

Other than that, your config looks fine. Just remember to name it `config.yaml` or specify the option `snakemake --configfile config.txt`. Can you please try to `git pull` the repo and [follow the instructions](https://github.com/conchoecia/odp#use-case---make-ribbon-diagrams-of-conserved-linkages-between-genomes), like you tried already, to see if the problem is resolved?

**Comment by Mia1349** [comment] 2023-05-31 02:46
Hi Darrin, 

Thank you for the quick reply!

I tried the new odp_rbh_to_ribbon script and unfortunately, it shuts down pretty much at the same spot. I am thinking maybe there are some confusion about the input files? 

I specified the directory containing the .rbh files like you suggested: 

rbh_directory: /home/liuhy/Source_Data/chequ/odp/new_odp/RBHs/TSS_TCS/odp/step2-figures/synteny_coloredby_BCnS_LGs/

Should I copy all four rbh files to this directory? because initially I tried to get the ribbon plot of five species. The rbh files were generated using the lastest odp pipeline(../scripts/odp). 

Then I conduct a testrun with only two species(BFL and PMA) but the problem presist, I attach the log file the the rbh file at the end, maybe they will be some help. I have to rename them to txt files for uploading issues..

Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 16
Rules claiming more threads will be scaled down.
Job stats:
job                 count    min threads    max threads
----------------  -------  -------------  -------------
all                     1              1              1
make_plot               1              1              1
sp_to_chr_to_len        1              1              1
total                   3              1              1

Select jobs to execute...
[BFL_PMA_xy_reciprocal_best_hits.coloredby_BCnS_LGs.plotted.txt](https://github.com/conchoecia/odp/files/11608088/BFL_PMA_xy_reciprocal_best_hits.coloredby_BCnS_LGs.plotted.txt)
[config.txt](https://github.com/conchoecia/odp/files/11608089/config.txt)


[Thu Jun  1 10:17:26 2023]
rule sp_to_chr_to_len:
    output: sp_to_chr_to_size.tsv
    jobid: 2
    reason: Missing output files: sp_to_chr_to_size.tsv; Params have changed since last execution
    resources: tmpdir=/tmp

[Thu Jun  1 10:17:46 2023]
Finished job 2.
1 of 3 steps (33%) done
Select jobs to execute...

[Thu Jun  1 10:17:46 2023]
rule make_plot:
    input: /home/liuhy/Source_Data/chequ/odp/new_odp/RBHs/PMA_bran/odp/step2-figures/synteny_coloredby_BCnS_LGs/BFL_PMA_xy_reciprocal_best_hits.coloredby_BCnS_LGs.plotted.rbh, sp_to_chr_to_size.tsv
    output: output.pdf
    jobid: 1
    reason: Missing output files: output.pdf; Input files updated by another job: sp_to_chr_to_size.tsv
    resources: tmpdir=/tmp

sp: PMA, num_chroms: 19, percent_chrom_as_spaces: 0.2055
sp: BFL, num_chroms: 19, percent_chrom_as_spaces: 0.2055
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: .snakemake/log/2023-06-01T101724.081863.snakemake.log
(snakemake_env) [liuhy@X940xa-node2 two_species]$ ls
config.yaml  sp_to_chr_to_size.tsv
(snakemake_env) [liuhy@X940xa-node2 two_species]$ ls
config.yaml  sp_to_chr_to_size.tsv
(snakemake_env) [liuhy@X940xa-node2 two_species]$ snakemake --cores 16 --snakefile /home/liuhy/synteny/odp-main/scripts/odp_rbh_to_ribbon
Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 16
Rules claiming more threads will be scaled down.
Job stats:
job          count    min threads    max threads
---------  -------  -------------  -------------
all              1              1              1
make_plot        1              1              1
total            2              1              1

Select jobs to execute...

[Thu Jun  1 10:31:03 2023]
rule make_plot:
    input: /home/liuhy/Source_Data/chequ/odp/new_odp/RBHs/PMA_bran/odp/step2-figures/synteny_coloredby_BCnS_LGs/BFL_PMA_xy_reciprocal_best_hits.coloredby_BCnS_LGs.plotted.rbh, sp_to_chr_to_size.tsv
    output: output.pdf
    jobid: 1
    reason: Missing output files: output.pdf
    resources: tmpdir=/tmp

sp: PMA, num_chroms: 19, percent_chrom_as_spaces: 0.2055
sp: BFL, num_chroms: 19, percent_chrom_as_spaces: 0.2055
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: .snakemake/log/2023-06-01T103101.745486.snakemake.log
[BFL_PMA_xy_reciprocal_best_hits.coloredby_BCnS_LGs.plotted.txt](https://github.com/conchoecia/odp/files/11608091/BFL_PMA_xy_reciprocal_best_hits.coloredby_BCnS_LGs.plotted.txt)
[config.txt](https://github.com/conchoecia/odp/files/11608092/config.txt)

**Comment by conchoecia** [comment] 2023-06-01 15:26
> Should I copy all four rbh files to this directory? because initially I tried to get the ribbon plot of five species. The rbh files were generated using the lastest odp pipeline(../scripts/odp).

This bit makes it sound like the directory of `.rbh` files the the `config.yaml` file might be missing something. All of the species for which you want to make a ribbon diagram need to be run through the regular `scripts/odp` pipeline. Then the `odp_rbh_to_ribbon` can be run on the folder containing the `.rbh` files.

I made some changes to `odp_rbh_to_ribbon` that will catch problems with missing samples and let you know what is wrong. Try a `git pull` from the software install directory to update the software to the latest version, then try again.

If there is some problem let me know!

**Comment by Mia1349** [comment] 2023-06-02 13:03
Hi darrin!

Sorry for the late reply.  I performed a test run with the lastest scripts and it worked!  Thank you so much for the update. A small question though...

I used a part of your data and tried to recreate Fig.1d in the paper,  I attached the ribbon plot I got. How could I filter out the black lines? Maybe there is a parameter I could change? 
<img width="1072" alt="image" src="https://github.com/conchoecia/odp/assets/77708840/2d51d565-f98a-4676-bb1e-ccbd15e9478c">

Mia

**Comment by conchoecia** [comment] 2023-06-02 14:42
That is great, Mia! Glad it worked for you.

If you want to remove the grey lines in the background you can do so with a vector graphic editing software (Inkscape/Adobe Illustrator), or re-run the software with the option `plot_all: False`.

Looks like you ran it with `plot_all: True`, because the non-significant interactions are light gray (0.15 opacity).

I will close this issue, but feel free to re-open this if you have another relevant question. If you have an unrelated problem or suggestion to improve the software please open a new issue.

**Closed by conchoecia** 2023-06-02 14:42 UTC
